# Generated by Django 3.2.18 on 2023-04-19 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='dynamic'),
            preserve_default=False,
        ),
    ]
